export const ProjectScope = [
  {
    order_no: 1,
    title: "General",
    questions: [
      {
        order_no: 1,
        question: "Describe the AI environment/application used.",
        hint: "Describe the AI environment/application used.",
        priority_level: "high priority",
        answer_type: "Long text",
        input_type: "Tiptap area",
        evidence_required: false,
        isrequired: true,
        evidence_files: [],
        dropdown_options: [],
      },
      {
        order_no: 2,
        question: "Is a new form of AI technology used?",
        hint: "Is a new form of AI technology used?",
        priority_level: "high priority",
        answer_type: "Long text",
        input_type: "Tiptap area",
        evidence_required: false,
        isrequired: true,
        evidence_files: [],
        dropdown_options: [],
      },
      {
        order_no: 3,
        question: "Are personal sensitive data used?",
        hint: "Are personal sensitive data used?",
        priority_level: "high priority",
        answer_type: "Long text",
        input_type: "Tiptap area",
        evidence_required: false,
        isrequired: true,
        evidence_files: [],
        dropdown_options: [],
      },
      {
        order_no: 4,
        question: "Project scope documents description",
        hint: "Project scope documents description",
        priority_level: "high priority",
        answer_type: "Long text",
        input_type: "Tiptap area",
        evidence_required: false,
        isrequired: true,
        evidence_files: [],
        dropdown_options: [],
      },
    ],
  },
  {
    order_no: 2,
    title: "Technology details",
    questions: [
      {
        order_no: 1,
        question:
          "What type of AI technology are you using? Explain AI and ML technologies used.",
        hint: "What type of AI technology are you using? Explain AI and ML technologies used.",
        priority_level: "high priority",
        answer_type: "Long text",
        input_type: "Tiptap area",
        evidence_required: false,
        isrequired: true,
        evidence_files: [],
        dropdown_options: [],
      },
      {
        order_no: 2,
        question:
          "Is there ongoing monitoring of the system to ensure that the system is operating as intended?",
        hint: "Is there ongoing monitoring of the system to ensure that the system is operating as intended?",
        priority_level: "high priority",
        answer_type: "Long text",
        input_type: "Tiptap area",
        evidence_required: false,
        isrequired: true,
        evidence_files: [],
        dropdown_options: [],
      },
      {
        order_no: 3,
        question:
          "Have you considered unintended outcomes that could occur from the use of this system?",
        hint: "Have you considered unintended outcomes that could occur from the use of this system?",
        priority_level: "high priority",
        answer_type: "Long text",
        input_type: "Tiptap area",
        evidence_required: false,
        isrequired: true,
        evidence_files: [],
        dropdown_options: [],
      },
      {
        order_no: 4,
        question:
          "Add technology documentation. You can include a data flow diagram, MLops lifecycle diagram. Think of it as an executive summary of the technology you are using.",
        hint: "Add technology documentation. You can include a data flow diagram, MLops lifecycle diagram. Think of it as an executive summary of the technology you are using.",
        priority_level: "high priority",
        answer_type: "Long text",
        input_type: "Tiptap area",
        evidence_required: false,
        isrequired: true,
        evidence_files: [],
        dropdown_options: [],
      },
    ],
  },
];
