export type AnnexCategoryStructISO = {
  id?: number; // auto generated by database
  title: string;
  description: string;
  guidance: string;
  sub_id: number;
  order_no?: number;
  annex_id?: number;
};
