import { Status } from "./Status";

export type AnnexCategoryISO = {
  id?: number; // auto generated by database
  is_applicable: boolean;
  justification_for_exclusion: string;
  implementation_description: string;
  evidence_links: Object[];
  status: Status;
  owner: number;
  reviewer: number;
  approver: number;
  due_date: Date;
  auditor_feedback: string;
  projects_frameworks_id: number;
  annexcategory_meta_id: number;
  created_at: Date;
  is_demo?: boolean;
};
