import { AnnexCategoryISO } from "./AnnexCategoryISO";
import { AnnexCategoryStructISO } from "./AnnexCategoryStructISO";

export type AnnexStructISO = {
  id?: number; // auto generated by database
  title: string; // gets assigned from the structure
  annex_no?: number; // gets assigned from the structure
  framework_id?: number; // gets assigned from the structure
  annexCategories: Partial<AnnexCategoryISO & AnnexCategoryStructISO>[];
};
