export type AnnexStructISO = {
  id?: number; // auto generated by database
  title: string; // gets assigned from the structure
  annex_no?: number; // gets assigned from the structure
  framework_id?: number; // gets assigned from the structure
  annexcategories: Partial<AnnexCategoryISO & AnnexCategoryStructISO>[];
};
