import { SubClauseISO } from "./SubClauseISO";
import { SubClauseStructISO } from "./SubClauseStructISO";

export type ClauseStructISO = {
  id?: number; // auto generated by database
  title: string; // gets assigned from the structure
  clause_no: number; // gets assigned from the structure
  framework_id?: number; // gets assigned from the structure
  subClauses: Partial<SubClauseISO & SubClauseStructISO>[];
};
