/**
 * Represents a user role in the system.
 * Maps to the roles table in the database.
 */
export type Role = {
  /** Unique identifier for the role (auto-generated by database) */
  id: number;
  /** Display name of the role (e.g., "Admin", "User", "Auditor") */
  name: string;
  /** Detailed description of the role's permissions and purpose */
  description: string;
  /** Timestamp when the role was created */
  created_at?: Date;
};
