import { Status } from "./Status";

export type SubClauseISO = {
  title: string;
  id?: number; // auto generated by database
  implementation_description: string;
  evidence_links: Object[];
  status: Status;
  owner: number;
  reviewer: number;
  approver: number;
  due_date: Date;
  auditor_feedback: string;
  subclause_meta_id: number;
  projects_frameworks_id: number;
  created_at: Date;
  is_demo?: boolean;
};
