export type SubClauseStructISO = {
  id?: number; // auto generated by database
  title: string;
  order_no: number;
  summary: string;
  questions: string[];
  evidence_examples: string[];
  clause_id?: number;
};
