/**
 * Represents a user in the system.
 * Maps to the users table in the database.
 */
export type User = {
    /** Unique identifier for the user (auto-generated by database) */
    id: number;
    /** User's first name */
    name: string;
    /** User's surname/last name */
    surname: string;
    /** User's email address (used for login) */
    email: string;
    /** Hashed password (created by database) */
    password_hash?: string;
    /** Reference to user's role (backend field name) */
    role_id?: number;
    /** Reference to user's role (frontend compatibility) */
    roleId?: number;
    /** Timestamp when the user was created */
    created_at?: Date;
    /** Timestamp of user's last login */
    last_login?: Date;
    /** Flag indicating if this is a demo user */
    is_demo?: boolean;
    /** Reference to user's organization */
    organization_id?: number;
    /** Flag indicating if password has been set */
    pwd_set?: boolean;
};

/**
 * Generic API response wrapper.
 * @template T - The type of data contained in the response
 */
export interface ApiResponse<T> {
    /** The response payload */
    data: T;
    /** HTTP status code */
    status: number;
    /** Optional message from the API */
    message?: string;
}

/**
 * Content structure for binary photo data.
 */
export interface PhotoContent {
    /** Raw binary data as array of bytes */
    data?: number[];
}

/**
 * Photo data structure returned from the API.
 */
export interface PhotoData {
    /** Binary content of the photo */
    content: ArrayBuffer | number[] | PhotoContent;
    /** MIME type of the photo */
    type?: string;
    /** Alternative field for MIME type */
    mimeType?: string;
    /** Alternative field for content type */
    contentType?: string;
}

/**
 * Response structure from profile photo API endpoints.
 */
export interface ProfilePhotoApiResponse {
    /** Photo data wrapper */
    data?: {
        /** Photo information */
        photo?: PhotoData | null;
    };
    /** Direct photo URL (alternative format) */
    photoUrl?: string;
    /** Response message */
    message?: string;
}