export type VendorRisk = {
  risk_id?: number; // auto generated by database
  vendor_id?: number; // won't get any values, will be filled by user
  project_id?: number; // the project this risk belongs to
  order_no?: number; // gets assigned from the structure
  risk_description: string;
  impact_description: string;
  impact: "Negligible" | "Minor" | "Moderate" | "Major" | "Critical";
  likelihood: "Rare" | "Unlikely" | "Possible" | "Likely" | "Almost certain";
  risk_severity: "Negligible" | "Minor" | "Moderate" | "Major" | "Catastrophic";
  action_plan: string;
  action_owner: number;
  risk_level: string;
  vendor_name: string;
  is_deleted?: boolean;
  deleted_at?: Date;
};

/**
 * Input type for creating a new vendor risk.
 * Excludes risk_id since it's auto-generated by the database.
 */
export type CreateVendorRiskInput = Partial<Omit<VendorRisk, "risk_id">>;

/**
 * Input type for updating an existing vendor risk.
 * All fields optional except what's being updated.
 */
export type UpdateVendorRiskInput = Partial<Omit<VendorRisk, "risk_id">>;
