/**
 * Represents a vendor risk assessment in the system.
 * Contains risk details, impact assessment, and mitigation plans.
 */
export type VendorRisk = {
  /** Unique identifier for the risk (auto-generated by database) */
  risk_id?: number;
  /** Reference to the vendor this risk is associated with */
  vendor_id?: number;
  /** Reference to the project this risk belongs to */
  project_id?: number;
  /** Order number for display purposes (assigned from structure) */
  order_no?: number;
  /** Detailed description of the identified risk */
  risk_description: string;
  /** Description of the potential impact if risk materializes */
  impact_description: string;
  /** Severity of impact on a 5-point scale */
  impact: "Negligible" | "Minor" | "Moderate" | "Major" | "Critical";
  /** Probability of risk occurrence on a 5-point scale */
  likelihood: "Rare" | "Unlikely" | "Possible" | "Likely" | "Almost Certain";
  /** Overall risk severity classification */
  risk_severity: "Negligible" | "Minor" | "Moderate" | "Major" | "Catastrophic";
  /** Planned actions to mitigate or address the risk */
  action_plan: string;
  /** User ID of the person responsible for risk mitigation */
  action_owner: number;
  /** Calculated risk level based on impact and likelihood */
  risk_level: string;
  /** Display name of the associated vendor */
  vendor_name: string;
  /** Soft delete flag */
  is_deleted?: boolean;
  /** Timestamp when the risk was soft deleted */
  deleted_at?: Date;
};

/**
 * Input type for creating a new vendor risk.
 * Uses Partial to allow flexibility in what fields are provided.
 * Backend handles defaults for missing fields.
 */
export type CreateVendorRiskInput = Partial<Omit<VendorRisk, 'risk_id' | 'is_deleted' | 'deleted_at'>>;

/**
 * Input type for updating an existing vendor risk.
 * All fields are optional except those required for identification.
 */
export type UpdateVendorRiskInput = Partial<Omit<VendorRisk, 'risk_id'>>;
