### get all assessments

GET http://localhost:3000/assessments

### get assessment by id

GET http://localhost:3000/assessments/2

###
POST http://localhost:3000/autoDrivers

###
DELETE  http://localhost:3000/autoDrivers