### get all projects

GET http://localhost:3000/projects

### get project stats

GET http://localhost:3000/projects/stats/1

### get project by id

GET http://localhost:3000/projects/2

### get project by id

GET http://localhost:3000/projects/compliance/progress/1

### get project by id

GET http://localhost:3000/projects/assessment/progress/1

### get project by id

GET http://localhost:3000/projects/all/compliance/progress

### get project by id

GET http://localhost:3000/projects/all/assessment/progress

