### get all projects

GET http://localhost:3000/projects
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlbWFpbEBlbWFpbC5jb20iLCJleHBpcmUiOjE3NDQwOTk4NzEyNDMsImlhdCI6MTc0NDA5NjI3MX0.QlTV7QqQThdRXmkLit-leWoo10VftPOUi0rZPfVJr50



### get project stats

GET http://localhost:3000/projects/stats/1

### get project by id

GET http://localhost:3000/projects/2

### get project by id

GET http://localhost:3000/projects/compliance/progress/1

### get project by id

GET http://localhost:3000/projects/assessment/progress/1

### get project by id

GET http://localhost:3000/projects/all/compliance/progress
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlbWFpbEBlbWFpbC5jb20iLCJleHBpcmUiOjE3NDQwOTk4NzEyNDMsImlhdCI6MTc0NDA5NjI3MX0.QlTV7QqQThdRXmkLit-leWoo10VftPOUi0rZPfVJr50


### get project by id

GET http://localhost:3000/projects/all/assessment/progress
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlbWFpbEBlbWFpbC5jb20iLCJleHBpcmUiOjE3NDQwOTk4NzEyNDMsImlhdCI6MTc0NDA5NjI3MX0.QlTV7QqQThdRXmkLit-leWoo10VftPOUi0rZPfVJr50
