### GET all roles

GET http://localhost:3000/roles

### GET role by id

GET http://localhost:3000/roles/2

### POST (create) a new role

POST http://localhost:3000/roles
Content-Type: application/json 

{
    "id": 8,
    "name": "admin",
    "description": "Can do anything"
}

### 

PATCH  http://localhost:3000/roles/1

###

DELETE http://localhost:3000/roles/1