import { useState, useEffect, useContext } from 'react'
import { Stack } from '@mui/material';
import ReportTable from '../../../components/Table/ReportTable';
import { VerifyWiseContext } from '../../../../application/contexts/VerifyWise.context';


const TITLE_OF_COLUMNS = [
  "REPORT NAME",
  "TYPE OF REPORT",
  "DATE GENERATED",
  "GENERATED BY",
  "ACTION"
];
/** Temporary demo data */
const data = [
  {
    report_name: "Assessment report May",
    type: "Assessment tracker report",
    date: "",
    generated_by: "Billy"
  }
]

const Reports = () => {
  const [ reports, setReports ] = useState<any[]>(data);
  const { dashboardValues } = useContext(VerifyWiseContext);
  const { selectedProjectId} = dashboardValues

  const fetchGeneratedReports = async() => {
    // Call backend API
  }

  useEffect(() => {
    if(selectedProjectId){
      fetchGeneratedReports();
    }
  }, [selectedProjectId])

  const handleRemoveReport = () => {
    // function for remove report 
  }

  return (
    <Stack sx={{pt: "1rem"}}>
      <ReportTable
        columns={TITLE_OF_COLUMNS}
        rows={reports}
        removeReport={handleRemoveReport}
      />
    </Stack>
  )
}

export default Reports