import { useState, useEffect, useContext } from 'react'
import { Stack } from '@mui/material';
import ReportTable from '../../../components/Table/ReportTable';
import { VerifyWiseContext } from '../../../../application/contexts/VerifyWise.context';

const TITLE_OF_COLUMNS = [
  "REPORT NAME",
  "TYPE OF REPORT",
  "DATE GENERATED",
  "GENERATED BY",
  "ACTION"
];
/** Temporary demo data */
const data = [
  {
    report_name: "Assessment report May",
    type: "Assessment tracker report",
    date: "",
    generated_by: "Billy"
  }
]

const Reports = () => {
  const [ reports, setReports ] = useState<any[]>([]);
  const { dashboardValues } = useContext(VerifyWiseContext);
  const { selectedProjectId} = dashboardValues;
  const [currentPage, setCurrentPage] = useState(0);

  const fetchGeneratedReports = async() => {
    // Call backend API
    setReports(data)
  }

  useEffect(() => {
    console.log('ss', dashboardValues)
    console.log('id', selectedProjectId)
    if(selectedProjectId){
      fetchGeneratedReports();
    }else{
      setReports([])
    }
  }, [selectedProjectId])

  const handleRemoveReport = () => {
    // function for remove report 
  }

  const setCurrentPagingation = (page: number) => {
    setCurrentPage(page)
  }

  return (
    <Stack sx={{pt: "1rem"}}>
      <ReportTable
        columns={TITLE_OF_COLUMNS}
        rows={reports}
        removeReport={handleRemoveReport}
        setPage={setCurrentPagingation}
        page={currentPage}
      />
    </Stack>
  )
}

export default Reports