import React from 'react'

const TITLE_OF_COLUMNS = [
  "REPORT NAME",
  "TYPE OF REPORT",
  "DATE GENERATED",
  "GENERATED BY",
  "ACTION"
];

const Reports = () => {
  return (
    <div>Reports</div>
  )
}

export default Reports