export const TITLE_OF_COLUMNS = [
  "REPORT NAME",
  "TYPE OF REPORT",
  "DATE GENERATED",
  "GENERATED BY",
  "ACTION"
];

export const DEMO_DATA = [
  {
    id: 1,
    report_name: "Assessment report May",
    type: "Assessment tracker report",
    date: "",
    generated_by: 1
  }
]