import { Column, DataType, Model, Table } from "sequelize-typescript";

/**
 * Training Registry Model:
 *  - Training Name: string
 *  - Duration: integer
 *  - Provider: string
 *  - Department: string
 *  - Status: <tags>
 *  - People: integer
 */

// DOULE CHECK: On creating a foreign key when you want toconnet this db to the admin
export type TrainingRegistar = {
  id?: number; // auto generated by DB
  training_name: string;
  duration: string;
  provider: string;
  department: string;
  status: "Planned" | "In Progress" | "Completed";
  numberOfPeople: number;
  description: string;
};

@Table({
  tableName: "trainingregistar",
})
export class TrainingRegistarModel extends Model<TrainingRegistar> {
  @Column({
    type: DataType.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  })
  id?: number;
  @Column({
    type: DataType.STRING,
  })
  training_name!: string;

  @Column({
    type: DataType.STRING,
  })
  duration!: string;

  @Column({
    type: DataType.STRING,
  })
  provider!: string;

  @Column({
    type: DataType.STRING,
  })
  department!: string;

  @Column({
    type: DataType.ENUM("Planned", "In Progress", "Completed"),
  })
  status!: "Planned" | "In Progress" | "Completed";

  @Column({
    type: DataType.INTEGER,
  })
  numberOfPeople!: number;

  @Column({
    type: DataType.STRING,
  })
  description!: string;
}
