version: '3.9'

services:
  backend:
    build:
      context: ./Servers
      dockerfile: Dockerfile.dev
    # volumes:
    #   - ./Servers/:/app
    env_file:
      - ./.env.dev

  frontend:
    build:
      context: ./Clients
      dockerfile: Dockerfile.dev
    volumes:
      - ./Clients/src:/app/src
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
    env_file:
      - ./.env.dev
    environment:
      - VITE_APP_PORT=$FRONTEND_PORT

  bias_and_fairness_backend:
    build:
      context: ./BiasAndFairnessServers
      dockerfile: Dockerfile.dev
    volumes:
      - ./BiasAndFairnessServers/src:/app
