import {
  Column,
  DataType,
  ForeignKey,
  Model,
  Table,
} from "sequelize-typescript";
import { ControlEUModel } from "./controlEU.model";
import { UserModel } from "../../models/user/user.model";

/*

This is the new Subcontrol model(Schema) and will be replaced with the new one.
Please align other files with this

*/
export type SubcontrolStructEU = {
  id?: number; // auto generated by database
  title: string; // gets assigned from the structure
  description: string; // gets assigned from the structure
  order_no?: number; // gets assigned from the structure
  control_id: number; // when control is created, its id will be stored and assign here as FK
};

@Table({
  tableName: "subcontrols",
})
export class SubcontrolStructEUModel extends Model<SubcontrolStructEU> {
  @Column({
    type: DataType.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  })
  id?: number;

  @Column({
    type: DataType.STRING,
  })
  title!: string;

  @Column({
    type: DataType.STRING,
  })
  description!: string;

  @Column({
    type: DataType.INTEGER,
  })
  order_no?: number;

  @ForeignKey(() => ControlEUModel)
  @Column({
    type: DataType.INTEGER,
  })
  control_id!: number;

  @Column({
    type: DataType.BOOLEAN,
    allowNull: false,
    defaultValue: false,
  })
  is_demo?: boolean;
}
