import {
  Column,
  DataType,
  ForeignKey,
  Model,
  Table,
} from "sequelize-typescript";
import { FrameworkModel } from "../../models/frameworks/frameworks.model";

/*

This is the new Topic model(Schema) and will be replaced with the new one.
Please align other files with this

*/
export type TopicStructEU = {
  id?: number; // auto generated by database
  title: string; // gets assigned from the structure
  order_no?: number; // gets assigned from the structure
  framework_id?: number; // gets assigned from the structure
};

@Table({
  tableName: "topics",
})
export class TopicStructEUModel extends Model<TopicStructEU> {
  @Column({
    type: DataType.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  })
  id?: number;

  @Column({
    type: DataType.STRING,
  })
  title!: string;

  @Column({
    type: DataType.INTEGER,
  })
  order_no?: number;

  @ForeignKey(() => FrameworkModel)
  @Column({
    type: DataType.INTEGER,
  })
  framework_id?: number;

  @Column({
    type: DataType.BOOLEAN,
    allowNull: false,
    defaultValue: false,
  })
  is_demo?: boolean;
}
