/**
 * Security utilities for input validation and sanitization
 */

/**
 * Validates that a string contains only alphanumeric characters and underscores
 * Used for schema names, table names, and other SQL identifiers
 *
 * @param value - The value to validate
 * @returns true if valid, false otherwise
 */
export function isValidSQLIdentifier(value: string): boolean {
  // Allow only alphanumeric and underscore (safe for SQL identifiers)
  // Max length 63 for PostgreSQL identifier
  return /^[a-zA-Z0-9_]{1,63}$/.test(value);
}

/**
 * Validates tenant hash format
 * Tenant hashes should be base64-like strings
 *
 * @param tenantId - The tenant ID to validate
 * @returns true if valid tenant hash format
 */
export function isValidTenantHash(tenantId: string): boolean {
  // getTenantHash produces base64-like strings, typically 10-20 chars
  // Allow alphanumeric characters only (base64 without special chars)
  return /^[a-zA-Z0-9]{8,64}$/.test(tenantId);
}

/**
 * Validates resource type against allowed values
 *
 * @param resourceType - The resource type to validate
 * @returns true if valid resource type
 */
export function isValidResourceType(resourceType: string): boolean {
  const allowedTypes = ['model', 'vendor', 'project', 'policy', 'risk'];
  return allowedTypes.includes(resourceType);
}

/**
 * Validates share token format
 * Tokens should be 64-character hex strings generated by crypto.randomBytes(32)
 *
 * @param token - The token to validate
 * @returns true if valid token format
 */
export function isValidShareToken(token: string): boolean {
  // Exactly 64 hex characters (32 bytes = 64 hex chars)
  return /^[a-f0-9]{64}$/.test(token);
}

/**
 * Sanitizes error messages for safe display to users
 * Removes sensitive information like file paths, SQL details, etc.
 *
 * @param error - The error object
 * @param defaultMessage - Default message to return if sanitization needed
 * @returns Sanitized error message
 */
export function sanitizeErrorMessage(error: Error, defaultMessage: string = "An error occurred"): string {
  const message = error.message || "";

  // List of patterns that indicate sensitive information
  const sensitivePatterns = [
    /\/.*\//,  // File paths
    /at\s+.*\s+\(/,  // Stack traces
    /column/i,  // SQL column references
    /table/i,  // SQL table references
    /relation/i,  // PostgreSQL relation errors
    /schema/i,  // Schema references
    /password/i,  // Password mentions
    /token/i,  // Token values (but allow "token" as generic word)
    /secret/i,  // Secret mentions
  ];

  // Check if message contains sensitive info
  for (const pattern of sensitivePatterns) {
    if (pattern.test(message)) {
      return defaultMessage;
    }
  }

  // If no sensitive patterns found, return original message
  // but limit length
  return message.substring(0, 200);
}

/**
 * Creates a safe SQL identifier by validating and escaping if needed
 * IMPORTANT: Only use for identifiers (table/schema names), NOT for values
 *
 * @param identifier - The identifier to make safe
 * @throws Error if identifier is invalid
 * @returns The validated identifier
 */
export function safeSQLIdentifier(identifier: string): string {
  if (!isValidSQLIdentifier(identifier)) {
    throw new Error('Invalid SQL identifier');
  }
  return identifier;
}
