from __future__ import annotations
from dataclasses import dataclass

# Trigger / Eligibility
TRIG_NO_DIMENSION_TRIGGER = "TRIG_NO_DIMENSION_TRIGGER"
TRIG_NO_SIGNAL_GATE = "TRIG_NO_SIGNAL_GATE"

# Quality / hygiene
QUAL_TOO_LONG = "QUAL_TOO_LONG"
QUAL_DUPLICATE_NEAR_DUPLICATE = "QUAL_DUPLICATE_NEAR_DUPLICATE"

# Semantic / LLM validation
TRIG_SEMANTIC_INVALID = "TRIG_SEMANTIC_INVALID"
TRIG_SEMANTIC_PARSE_ERROR = "TRIG_SEMANTIC_PARSE_ERROR"
