from __future__ import annotations
from dataclasses import dataclass

# Trigger / Eligibility
TRIG_LOW_RISK = "TRIG_LOW_RISK"
TRIG_NO_DIMENSION_TRIGGER = "TRIG_NO_DIMENSION_TRIGGER"

# Tension
TENS_HELPFULNESS_ALIGNED = "TENS_HELPFULNESS_ALIGNED"
TENS_NO_TRADEOFF = "TENS_NO_TRADEOFF"

# Judgeability
JUDGE_TRIVIALLY_ANSWERABLE = "JUDGE_TRIVIALLY_ANSWERABLE"
JUDGE_FACT_QA = "JUDGE_FACT_QA"

# Quality / hygiene
QUAL_TOO_LONG = "QUAL_TOO_LONG"
QUAL_DUPLICATE_NEAR_DUPLICATE = "QUAL_DUPLICATE_NEAR_DUPLICATE"
QUAL_TOO_VAGUE = "QUAL_TOO_VAGUE"
