FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

COPY ./ ./

RUN pip install --no-cache-dir -r ./src/requirements.txt

CMD sh -c "uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload"
