import { Column, DataType, ForeignKey, Model, Table } from "sequelize-typescript";
import { TopicStructEUModel } from "./topicStructEU.model";

/*

This is the new Subtopic model(Schema) and will be replaced with the new one.
Please align other files with this

*/
export type SubtopicStructEU = {
  id?: number; // auto generated by database
  title: string; // gets assigned from the structure
  order_no?: number; // gets assigned from the structure
  topic_id: number; // when topic is created, its id will be stored and assign here as FK
};

@Table({
  tableName: "subtopics"
})
export class SubtopicStructEUModel extends Model<SubtopicStructEU> {
  @Column({
    type: DataType.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  })
  id?: number;

  @Column({
    type: DataType.STRING
  })
  title!: string;

  @Column({
    type: DataType.INTEGER
  })
  order_no?: number;

  @ForeignKey(() => TopicStructEUModel)
  @Column({
    type: DataType.INTEGER
  })
  topic_id!: number;

  @Column({
    type: DataType.BOOLEAN,
    allowNull: false,
    defaultValue: false
  })
  is_demo?: boolean;

}

