import { File } from "../../../../domain/File";

export const mockFiles: File[] = [
  {
    id: "1",
    name: "Quarterly Report Q1.pdf",
    type: "PDF",
    uploadDate: "2025-01-01",
    uploader: "Emily Chen",
  },
  {
    id: "2",
    name: "Marketing Strategy.png",
    type: "Image",
    uploadDate: "2025-01-02",
    uploader: "Ryan Thompson",
  },
  {
    id: "3",
    name: "Sales Presentation.pptx",
    type: "Presentation",
    uploadDate: "2025-01-03",
    uploader: "Samantha Lee",
  },
  {
    id: "4",
    name: "Financial Analysis.pdf",
    type: "PDF",
    uploadDate: "2025-01-04",
    uploader: "Michael Brown",
  },
  {
    id: "5",
    name: "Product Launch Image.png",
    type: "Image",
    uploadDate: "2025-01-05",
    uploader: "Olivia Martin",
  },
  {
    id: "6",
    name: "Training Session.pptx",
    type: "Presentation",
    uploadDate: "2025-01-06",
    uploader: "Alexander Davis",
  },
  {
    id: "7",
    name: "HR Policy Document.pdf",
    type: "PDF",
    uploadDate: "2025-01-07",
    uploader: "Isabella Garcia",
  },
  {
    id: "8",
    name: "Company Event Photo.png",
    type: "Image",
    uploadDate: "2025-01-08",
    uploader: "Benjamin Hall",
  },
  {
    id: "9",
    name: "Quarterly Sales Report.pptx",
    type: "Presentation",
    uploadDate: "2025-01-09",
    uploader: "Hannah Taylor",
  },
  {
    id: "10",
    name: "Annual Budget Proposal.pdf",
    type: "PDF",
    uploadDate: "2025-01-10",
    uploader: "Ethan White",
  },
  {
    id: "11",
    name: "New Product Design.png",
    type: "Image",
    uploadDate: "2025-01-11",
    uploader: "Lily Patel",
  },
  {
    id: "12",
    name: "Marketing Strategy Update.pptx",
    type: "Presentation",
    uploadDate: "2025-01-12",
    uploader: "Noah Walker",
  },
  {
    id: "13",
    name: "Financial Forecast.pdf",
    type: "PDF",
    uploadDate: "2025-01-13",
    uploader: "Ava Lewis",
  },
  {
    id: "14",
    name: "Product Launch Video.png",
    type: "Image",
    uploadDate: "2025-01-14",
    uploader: "Julian Brooks",
  },
  {
    id: "15",
    name: "Sales Performance Review.pptx",
    type: "Presentation",
    uploadDate: "2025-01-15",
    uploader: "Sophia Jenkins",
  },
  {
    id: "16",
    name: "HR Training Manual.pdf",
    type: "PDF",
    uploadDate: "2025-01-16",
    uploader: "Mia Harris",
  },
  {
    id: "17",
    name: "Company Event Flyer.png",
    type: "Image",
    uploadDate: "2025-01-17",
    uploader: "William Johnson",
  },
  {
    id: "18",
    name: "Quarterly Financial Report.pptx",
    type: "Presentation",
    uploadDate: "2025-01-18",
    uploader: "Charlotte Brown",
  },
  {
    id: "19",
    name: "Annual Report.pdf",
    type: "PDF",
    uploadDate: "2025-01-19",
    uploader: "Gabriel Davis",
  },
  {
    id: "20",
    name: "New Product Launch Image.png",
    type: "Image",
    uploadDate: "2025-01-20",
    uploader: "Abigail Martin",
  },
];
