export const ISO27001Annex = [
  {
    arrangement: "A",
    index: 5,
    category_name: "Organizational controls",
    controls: [
      {
        index: 1,
        title: "Policies for information security",
        requirement_summary:
          "Implement clear and effective measures for 'Policies for information security' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Policies for information security'?",
          "Who is responsible for ensuring 'Policies for information security' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description: "",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "Policy",
            relevance: "Medium",
          },
        ],
      },
      {
        index: 2,
        title: "Information security roles and responsibilities",
        requirement_summary:
          "Implement clear and effective measures for 'Information security roles and responsibilities' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Information security roles and responsibilities'?",
          "Who is responsible for ensuring 'Information security roles and responsibilities' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description: "",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "Policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 3,
        title: "Segregation of duties",
        requirement_summary:
          "Implement clear and effective measures for 'Segregation of duties' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Segregation of duties'?",
          "Who is responsible for ensuring 'Segregation of duties' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Segregation of duties' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "Policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 4,
        title: "Management responsibilities",
        requirement_summary:
          "Implement clear and effective measures for 'Management responsibilities' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Management responsibilities'?",
          "Who is responsible for ensuring 'Management responsibilities' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Management responsibilities' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "Policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 5,
        title: "Contact with authorities",
        requirement_summary:
          "Implement clear and effective measures for 'Contact with authorities' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Contact with authorities'?",
          "Who is responsible for ensuring 'Contact with authorities' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Contact with authorities' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "Policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 6,
        title: "Contact with special interest groups",
        requirement_summary:
          "Implement clear and effective measures for 'Contact with special interest groups' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Contact with special interest groups'?",
          "Who is responsible for ensuring 'Contact with special interest groups' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Contact with special interest groups' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "Policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 7,
        title: "Threat intelligence",
        requirement_summary:
          "Implement clear and effective measures for 'Threat intelligence' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Threat intelligence'?",
          "Who is responsible for ensuring 'Threat intelligence' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Threat intelligence' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "Policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 8,
        title: "Information security in project management",
        requirement_summary:
          "Implement clear and effective measures for 'Information security in project management' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Information security in project management'?",
          "Who is responsible for ensuring 'Information security in project management' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Information security in project management' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "Policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 9,
        title: "Inventory of information and assets",
        requirement_summary:
          "Implement clear and effective measures for 'Inventory of information and assets' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Inventory of information and assets'?",
          "Who is responsible for ensuring 'Inventory of information and assets' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Inventory of information and assets' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "Policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 10,
        title: "Acceptable use of information and assets",
        requirement_summary:
          "Implement clear and effective measures for 'Acceptable use of information and assets' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Acceptable use of information and assets'?",
          "Who is responsible for ensuring 'Acceptable use of information and assets' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Acceptable use of information and assets' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "Policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 11,
        title: "Return of assets",
        requirement_summary:
          "Implement clear and effective measures for 'Return of assets' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Return of assets'?",
          "Who is responsible for ensuring 'Return of assets' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Return of assets' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "Policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 12,
        title: "Classification of information",
        requirement_summary:
          "Implement clear and effective measures for 'Classification of information' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Classification of information'?",
          "Who is responsible for ensuring 'Classification of information' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Classification of information' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "Policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 13,
        title: "Labelling of information",
        requirement_summary:
          "Implement clear and effective measures for 'Labelling of information' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Labelling of information'?",
          "Who is responsible for ensuring 'Labelling of information' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Labelling of information' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "Policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 14,
        title: "Handling of information",
        requirement_summary:
          "Implement clear and effective measures for 'Handling of information' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Handling of information'?",
          "Who is responsible for ensuring 'Handling of information' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Handling of information' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 15,
        title: "Access control policy",
        requirement_summary:
          "Implement clear and effective measures for 'Access control policy' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Access control policy'?",
          "Who is responsible for ensuring 'Access control policy' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Access control policy' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 16,
        title: "Access to networks and network services",
        requirement_summary:
          "Implement clear and effective measures for 'Access to networks and network services' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Access to networks and network services'?",
          "Who is responsible for ensuring 'Access to networks and network services' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Access to networks and network services' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 17,
        title: "User registration and de-registration",
        requirement_summary:
          "Implement clear and effective measures for 'User registration and de-registration' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'User registration and de-registration'?",
          "Who is responsible for ensuring 'User registration and de-registration' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'User registration and de-registration' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 18,
        title: "Management of privileged access rights",
        requirement_summary:
          "Implement clear and effective measures for 'Management of privileged access rights' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Management of privileged access rights'?",
          "Who is responsible for ensuring 'Management of privileged access rights' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Management of privileged access rights' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 19,
        title: "Management of secret authentication information",
        requirement_summary:
          "Implement clear and effective measures for 'Management of secret authentication information' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Management of secret authentication information'?",
          "Who is responsible for ensuring 'Management of secret authentication information' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Management of secret authentication information' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 20,
        title: "Review of user access rights",
        requirement_summary:
          "Implement clear and effective measures for 'Review of user access rights' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Review of user access rights'?",
          "Who is responsible for ensuring 'Review of user access rights' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Review of user access rights' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 21,
        title: "Removal or adjustment of access rights",
        requirement_summary:
          "Implement clear and effective measures for 'Removal or adjustment of access rights' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Removal or adjustment of access rights'?",
          "Who is responsible for ensuring 'Removal or adjustment of access rights' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Removal or adjustment of access rights' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 22,
        title: "Use of secret authentication information",
        requirement_summary:
          "Implement clear and effective measures for 'Use of secret authentication information' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Use of secret authentication information'?",
          "Who is responsible for ensuring 'Use of secret authentication information' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Use of secret authentication information' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 23,
        title: "Information security in supplier relationships",
        requirement_summary:
          "Implement clear and effective measures for 'Information security in supplier relationships' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Information security in supplier relationships'?",
          "Who is responsible for ensuring 'Information security in supplier relationships' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Information security in supplier relationships' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 24,
        title: "Addressing information security within supplier agreements",
        requirement_summary:
          "Implement clear and effective measures for 'Addressing information security within supplier agreements' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Addressing information security within supplier agreements'?",
          "Who is responsible for ensuring 'Addressing information security within supplier agreements' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Addressing information security within supplier agreements' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 25,
        title: "Information and communication technology supply chain security",
        requirement_summary:
          "Implement clear and effective measures for 'Information and communication technology supply chain security' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Information and communication technology supply chain security'?",
          "Who is responsible for ensuring 'Information and communication technology supply chain security' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Information and communication technology supply chain security' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 26,
        title: "Monitoring, review, and change management of supplier services",
        requirement_summary:
          "Implement clear and effective measures for 'Monitoring, review, and change management of supplier services' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Monitoring, review, and change management of supplier services'?",
          "Who is responsible for ensuring 'Monitoring, review, and change management of supplier services' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Monitoring, review, and change management of supplier services' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 27,
        title: "Incident management responsibilities and procedures",
        requirement_summary:
          "Implement clear and effective measures for 'Incident management responsibilities and procedures' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Incident management responsibilities and procedures'?",
          "Who is responsible for ensuring 'Incident management responsibilities and procedures' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Incident management responsibilities and procedures' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 28,
        title: "Reporting information security events",
        requirement_summary:
          "Implement clear and effective measures for 'Reporting information security events' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Reporting information security events'?",
          "Who is responsible for ensuring 'Reporting information security events' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Reporting information security events' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 29,
        title: "Reporting information security weaknesses",
        requirement_summary:
          "Implement clear and effective measures for 'Reporting information security weaknesses' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Reporting information security weaknesses'?",
          "Who is responsible for ensuring 'Reporting information security weaknesses' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Reporting information security weaknesses' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 30,
        title: "Assessment and decision on information security events",
        requirement_summary:
          "Implement clear and effective measures for 'Assessment and decision on information security events' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Assessment and decision on information security events'?",
          "Who is responsible for ensuring 'Assessment and decision on information security events' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Assessment and decision on information security events' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 31,
        title: "Response to information security incidents",
        requirement_summary:
          "Implement clear and effective measures for 'Response to information security incidents' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Response to information security incidents'?",
          "Who is responsible for ensuring 'Response to information security incidents' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Response to information security incidents' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 32,
        title: "Learning from information security incidents",
        requirement_summary:
          "Implement clear and effective measures for 'Learning from information security incidents' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Learning from information security incidents'?",
          "Who is responsible for ensuring 'Learning from information security incidents' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Learning from information security incidents' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 33,
        title: "Collection of evidence",
        requirement_summary:
          "Implement clear and effective measures for 'Collection of evidence' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Collection of evidence'?",
          "Who is responsible for ensuring 'Collection of evidence' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Collection of evidence' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 34,
        title: "Business continuity planning for information security",
        requirement_summary:
          "Implement clear and effective measures for 'Business continuity planning for information security' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Business continuity planning for information security'?",
          "Who is responsible for ensuring 'Business continuity planning for information security' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Business continuity planning for information security' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 35,
        title: "Redundancy of information processing facilities",
        requirement_summary:
          "Implement clear and effective measures for 'Redundancy of information processing facilities' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Redundancy of information processing facilities'?",
          "Who is responsible for ensuring 'Redundancy of information processing facilities' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Redundancy of information processing facilities' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
      {
        index: 36,
        title: "Documented operating procedures",
        requirement_summary:
          "Implement clear and effective measures for 'Documented operating procedures' as part of organizational controls to keep information secure.",
        key_questions: [
          "Do we have a written, approved process for 'Documented operating procedures'?",
          "Who is responsible for ensuring 'Documented operating procedures' is followed correctly?",
          "Do we train staff or partners on this control?",
          "How do we check or monitor that this control works as expected?",
          "What actions do we take if this control fails or is not followed?",
          "Do we gather evidence regularly to prove compliance with this control?",
          "Has this control been updated to reflect new risks, technology, or regulations?",
        ],
        evidence_examples: [
          "Documented policy or operating procedure specific to this control",
          "Roles and responsibility assignments",
          "Training materials, completion records, or awareness emails",
          "System logs, monitoring reports, or access records",
          "Incident and corrective action reports involving this control",
          "Audit reports verifying control effectiveness",
          "Change management records for updates to this control",
        ],
        implementation_description:
          "Describe how 'Documented operating procedures' is planned, implemented, communicated, and reviewed. Include tools, systems, or teams responsible. Mention how often this control is tested and improved.",
        status: "",
        owner: "",
        reviewer: "",
        approver: "",
        due_date: "",
        cross_mappings: [
          {
            framework: "ISO 42001",
            clause_no: 5,
            order_no: 2,
            clause_title: "AI management policy",
            relevance: "High",
          },
        ],
      },
    ],
  },
];
