/**
 * Shadow AI Report Table
 *
 * Displays generated Shadow AI reports with download and delete actions.
 * Supports external data for grouped table view.
 */

import { useState, useEffect, useCallback } from "react";
import {
  Stack,
  Typography,
  IconButton,
  Box,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TablePagination,
} from "@mui/material";
import { Download, Trash2 } from "lucide-react";
import {
  getShadowAIReports,
  deleteShadowAIReport,
  ShadowAIReportListItem,
} from "../../../../application/repository/shadowAi.repository";
import { handleDownload } from "../../../../application/tools/fileDownload";
import TablePaginationActions from "../../../components/TablePagination";
import StandardModal from "../../../components/Modals/StandardModal";

interface ShadowAIReportTableProps {
  refreshKey: number;
  onReportsLoaded?: (count: number, data: ShadowAIReportListItem[]) => void;
  externalData?: ShadowAIReportListItem[];
}

export default function ShadowAIReportTable({
  refreshKey,
  onReportsLoaded,
  externalData,
}: ShadowAIReportTableProps) {
  const [reports, setReports] = useState<ShadowAIReportListItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(0);
  const rowsPerPage = 10;

  // Delete confirmation
  const [deleteTarget, setDeleteTarget] = useState<ShadowAIReportListItem | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);

  const loadReports = useCallback(async () => {
    setLoading(true);
    try {
      const data = await getShadowAIReports();
      const list = data || [];
      setReports(list);
      onReportsLoaded?.(list.length, list);
    } catch (error) {
      console.error("Failed to load Shadow AI reports:", error);
      setReports([]);
      onReportsLoaded?.(0, []);
    } finally {
      setLoading(false);
    }
  }, [onReportsLoaded]);

  useEffect(() => {
    loadReports();
  }, [loadReports, refreshKey]);

  const handleConfirmDelete = async () => {
    if (!deleteTarget) return;
    setIsDeleting(true);
    try {
      await deleteShadowAIReport(deleteTarget.id);
      setReports((prev) => {
        const next = prev.filter((r) => r.id !== deleteTarget.id);
        onReportsLoaded?.(next.length, next);
        return next;
      });
    } catch (error) {
      console.error("Failed to delete report:", error);
    } finally {
      setIsDeleting(false);
      setDeleteTarget(null);
    }
  };

  const handleDownloadReport = async (report: ShadowAIReportListItem) => {
    try {
      await handleDownload(String(report.id), report.filename);
    } catch (error) {
      console.error("Failed to download report:", error);
    }
  };

  // Use external data when provided (for grouped view), otherwise use internal state
  const displayData = externalData ?? reports;

  if (loading && !externalData) {
    return (
      <Box sx={{ py: 4, textAlign: "center" }}>
        <Typography sx={{ fontSize: 13, color: "#667085" }}>
          Loading reports...
        </Typography>
      </Box>
    );
  }

  if (displayData.length === 0) {
    return null;
  }

  const paginatedReports = externalData
    ? displayData
    : displayData.slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage);

  const headerCellSx = {
    fontSize: 12,
    fontWeight: 600,
    color: "#667085",
    textTransform: "uppercase" as const,
    letterSpacing: "0.3px",
    borderBottom: "1px solid #E4E7EC",
    py: 1.5,
    px: 2,
    backgroundColor: "#F9FAFB",
  };

  const bodyCellSx = {
    fontSize: 13,
    color: "#344054",
    borderBottom: "1px solid #F2F4F7",
    py: 1.5,
    px: 2,
  };

  return (
    <>
      <Stack gap="4px">
        <TableContainer
          sx={{
            border: "1px solid #E4E7EC",
            borderRadius: "4px",
            overflow: "hidden",
          }}
        >
          <Table size="small">
            <TableHead>
              <TableRow>
                <TableCell sx={headerCellSx}>Report name</TableCell>
                <TableCell sx={{ ...headerCellSx, width: 80 }}>Format</TableCell>
                <TableCell sx={{ ...headerCellSx, width: 180 }}>
                  Date generated
                </TableCell>
                <TableCell sx={{ ...headerCellSx, width: 160 }}>
                  Generated by
                </TableCell>
                <TableCell sx={{ ...headerCellSx, width: 80, textAlign: "right" }}>
                  Actions
                </TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {paginatedReports.map((report) => (
                <TableRow
                  key={report.id}
                  sx={{ "&:hover": { backgroundColor: "#F9FAFB" } }}
                >
                  <TableCell sx={{ ...bodyCellSx, fontWeight: 500 }}>
                    {report.filename}
                  </TableCell>
                  <TableCell sx={{ ...bodyCellSx, color: "#667085" }}>
                    {report.filename?.endsWith(".pdf") ? "PDF" : "DOCX"}
                  </TableCell>
                  <TableCell sx={{ ...bodyCellSx, color: "#667085" }}>
                    {report.uploaded_time
                      ? new Date(report.uploaded_time).toLocaleDateString(
                          "en-US",
                          {
                            year: "numeric",
                            month: "short",
                            day: "numeric",
                            hour: "2-digit",
                            minute: "2-digit",
                          }
                        )
                      : "-"}
                  </TableCell>
                  <TableCell sx={{ ...bodyCellSx, color: "#667085" }}>
                    {[report.uploader_name, report.uploader_surname]
                      .filter(Boolean)
                      .join(" ") || "-"}
                  </TableCell>
                  <TableCell sx={{ ...bodyCellSx, textAlign: "right" }}>
                    <Stack
                      direction="row"
                      spacing={0.5}
                      justifyContent="flex-end"
                    >
                      <IconButton
                        size="small"
                        aria-label="Download report"
                        onClick={() => handleDownloadReport(report)}
                        sx={{
                          color: "#667085",
                          "&:hover": { color: "#13715B" },
                        }}
                      >
                        <Download size={15} strokeWidth={1.5} />
                      </IconButton>
                      <IconButton
                        size="small"
                        aria-label="Delete report"
                        onClick={() => setDeleteTarget(report)}
                        sx={{
                          color: "#667085",
                          "&:hover": { color: "#B42318" },
                        }}
                      >
                        <Trash2 size={15} strokeWidth={1.5} />
                      </IconButton>
                    </Stack>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
        {!externalData && displayData.length > rowsPerPage && (
          <TablePagination
            component="div"
            count={displayData.length}
            page={page}
            onPageChange={(_, newPage) => setPage(newPage)}
            rowsPerPage={rowsPerPage}
            rowsPerPageOptions={[]}
            ActionsComponent={TablePaginationActions}
            sx={{
              borderTop: "none",
              ".MuiTablePagination-toolbar": {
                minHeight: 40,
                px: 2,
              },
              ".MuiTablePagination-displayedRows": {
                fontSize: 12,
                color: "#667085",
              },
            }}
          />
        )}
      </Stack>

      {/* Delete confirmation modal */}
      <StandardModal
        isOpen={!!deleteTarget}
        onClose={() => setDeleteTarget(null)}
        title="Delete report"
        description={`Are you sure you want to delete "${deleteTarget?.filename}"? This action cannot be undone.`}
        submitButtonText={isDeleting ? "Deleting..." : "Delete"}
        submitButtonColor="#c62828"
        onSubmit={handleConfirmDelete}
        maxWidth="440px"
      />
    </>
  );
}
