/**
 * Generates a report for EU AI Act or ISO 42001 frameworks
 * EU AI Act framwork report includes project risk, vendors and vendor risks, compliance tracker, and assessment tracker reports
 * ISO 42001 framework report includse project risk, vendors and vendor risks, annexes and clauses reports
 * @param frameworkId - The IDs of the framework: EU AI Act and ISO 42001
 * @param data - Project metadata including title and owner
 * @returns Promise<string> - Markdown formatted report
*/

import { ReportBodyData } from '../reportService';
import { getProjectRiskMarkdown } from './projectRiskMarkdown';

export async function getAllReportMarkdown (
    projectFrameworkId: number,
    projectId: number,
    data: ReportBodyData
  ) : Promise<any> {
  let rows: string;
  const projectReportData = await getProjectRiskMarkdown(projectId, data);

  const projectRiskMD = `
VerifyWise project report
========================

This report is generated by the VerifyWise. It aims to provide a way to demonstrate their claims about the risks of their AI systems.
  
- **Date** ${new Date().toLocaleDateString()}
- **Project** ${data.projectTitle}
- **Owner** ${data.projectOwner}

`
  return projectRiskMD;
}