/**
 * Generates a report for EU AI Act or ISO 42001 frameworks
 * EU AI Act framwork report includes project risk, vendors and vendor risks, compliance tracker, and assessment tracker reports
 * ISO 42001 framework report includse project risk, vendors and vendor risks, annexes and clauses reports
 * @param frameworkId - The IDs of the framework: EU AI Act and ISO 42001
 * @param data - Project metadata including title and owner
 * @returns Promise<string> - Markdown formatted report
*/

import { getAllFrameworkByIdQuery } from '../../utils/framework.utils';
import { ReportBodyData } from '../reportService';
import { getAssessmentTrackerReportData } from './assessmentTrackerMarkdown';
import { getComplianceReportData } from './complianceMarkdown';
import { getProjectRiskReportData } from './projectRiskMarkdown';
import { getVendorReportData, getVendorRiskReportData } from './vendorAndRisksMarkdown';

export async function getAllReportMarkdown (
  projectFrameworkId: number,
  projectId: number,
  data: ReportBodyData
) : Promise<any> {
  try {
    const framework = await getAllFrameworkByIdQuery(projectFrameworkId);

    if (framework) {
      let projectReportMarkdown = await getProjectRiskReportData(projectId);
      let vendorReportMarkdown = await getVendorReportData(projectId);
      let vendorRiskReportMarkdown = await getVendorRiskReportData(projectId);

      if (framework.name === "EU AI Act") { 
        const complianceReportMarkdown = await getComplianceReportData(projectFrameworkId);
        const assessmentReportMarkdown = await getAssessmentTrackerReportData(projectId, projectFrameworkId);

      const euAIMD = `
VerifyWise ${framework.name} report
========================

This report is generated by the VerifyWise. It aims to provide a way to demonstrate their claims about the risks of their AI systems.
  
- **Date** ${new Date().toLocaleDateString()}
- **Project** ${data.projectTitle}
- **Owner** ${data.projectOwner}

Project risk report
-------------
${projectReportMarkdown}

Vendor and vendor risk report
-------------
${vendorReportMarkdown}
${vendorRiskReportMarkdown}

Compliance tracker report
-------------
${complianceReportMarkdown}

Assessment tracker report
-------------
${assessmentReportMarkdown}
`
        return euAIMD;
      } else {
        

        const isoMD = `
VerifyWise ${framework.name} report
========================

This report is generated by the VerifyWise. It aims to provide a way to demonstrate their claims about the risks of their AI systems.
  
- **Date** ${new Date().toLocaleDateString()}
- **Project** ${data.projectTitle}
- **Owner** ${data.projectOwner}

Project risk report
-------------
${projectReportMarkdown}

Vendor and vendor risk report
-------------
${vendorReportMarkdown}
${vendorRiskReportMarkdown}

Clauses and annexes report
-------------
`
        return isoMD;
      }
    }
  } catch (error){
    throw new Error(`Error while fetching the project framework data`);    
  }
}