/**
 * Generates a markdown report for clauses and annexes
 * @param frameworkId - The ID of the framework: ISO 42001
 * @param data - Project metadata including title and owner
 * @returns Promise<string> - Markdown formatted clauses and annexes report
 */

import { AnnexCategoryStructISO } from "../../domain.layer/frameworks/ISO-42001/annexCategoryStructISO.model";
import { AnnexStructISOModel } from "../../domain.layer/frameworks/ISO-42001/annexStructISO.model";
import { getAnnexesReportQuery } from "../../utils/reporting.utils";
import { ReportBodyData } from "../reportService";
import { getClausesMarkdown } from "./clausesMarkdown";

type AnnexCategory = AnnexCategoryStructISO & {
  is_applicable: boolean;
  implementation_description: string;
  justification_for_exclusion: string;
};

type AllAnnexes = AnnexStructISOModel & {
  annexCategories: AnnexCategory[];
};

export async function getClausesAndAnnexesMarkdown(
  projectFrameworkId: number,
  data: ReportBodyData
): Promise<string> {
  const clausesAndAnnexesReportData = await getClausesAndAnnexesReportData(
    projectFrameworkId
  );

  const markdown = `
${data.organizationName || "VerifyWise"} clauses and annexes report
========================

This report is generated by the VerifyWise ISO 42001 framework. It aims to provide a way to demonstrate their claims about the risks of their AI systems.

- **Date** ${new Date().toLocaleDateString()}
- **Project** ${data.projectTitle}
- **Owner** ${data.projectOwner}

${clausesAndAnnexesReportData}
`;
  return markdown;
}

export async function getClausesAndAnnexesReportData(
  projectFrameworkId: number
): Promise<string> {
  let annexRows: string = ``;
  let clausesReportData: string = ``;
  try {
    const annexesReportData = (await getAnnexesReportQuery(
      projectFrameworkId
    )) as AllAnnexes[];
    clausesReportData = await getClausesMarkdown(projectFrameworkId);

    if (annexesReportData.length > 0) {
      annexRows = annexesReportData
        .map((annexes) => {
          const subAnnexes =
            annexes.annexCategories?.length > 0
              ? annexes.annexCategories
                  .map((annexCategory, i) => {
                    const status = annexCategory.is_applicable
                      ? `Implementation Description: ${annexCategory.implementation_description}`
                      : `Justification for Exclusion: ${annexCategory.justification_for_exclusion}}`;

                    const res = `__A${annexes.annex_no}${i + 1}. ${
                      annexCategory.title
                    }__ <br> Applicability: ${
                      annexCategory.is_applicable
                    }<br> ${status}`;
                    return `  - ${res}\n`;
                  })
                  .join("\n")
              : `No data`;

          return `__${annexes?.title}__\n${subAnnexes}\n`;
        })
        .join("\n");
    } else {
      annexRows = `-`;
    }
  } catch (error) {
    console.error(error);
    throw new Error(`Error while fetching the clauses and annexes data`);
  }

  return `
Clauses
-------------
${clausesReportData}

Annexes
-------------
${annexRows}
  `;
}
