import { ClauseStructISOModel } from '../../models/ISO-42001/clauseStructISO.model';
import { SubClauseStructISO } from '../../models/ISO-42001/subClauseStructISO.model';
import { Status } from '../../types/status.type';
import { getClausesReportQuery } from '../../utils/reporting.utils';
import { ReportBodyData } from '../reportService';

type SubClauses = SubClauseStructISO & {
  implementation_description: string;
  status: Status;
};

type AllClauses = ClauseStructISOModel & {
  subClauses: SubClauses[];
};

export async function getClausesMarkdown(
  frameworkId: number,
  data: ReportBodyData
): Promise<any> {
  const reportData = await getClausesReportQuery(frameworkId) as AllClauses[];

  const rows : string =
    reportData.length > 0
      ? reportData
          .map((clause) => {
            const subClauses = clause.subClauses
              .map((subClause, i) => {
                return `${clause.clause_no}.${i + 1} ${subClause.title} ${subClause.status}<br>`;
              })
              .join("\n");

            return `__${clause.title}__\n
${subClauses}\n`;
          })
          .join("\n")
      : `-`;

  return `
VerifyWise clauses report
=========================

This report is generated by the VerifyWise ISO 42001 framework. It aims to provide a way to demonstrate their claims about the risks of their AI systems.

- **Date** ${new Date().toLocaleDateString()}
- **Project** ${data.projectTitle}
- **Owner** ${data.projectOwner}

${rows}
`;
}