/**
 * Generates a markdown report for compliance tracker
 * @param frameworkId - The ID of the framework: EU AI Act
 * @param data - Project metadata including title and owner
 * @returns Promise<string> - Markdown formatted assessment tracker report
 */

import { ReportBodyData } from '../reportService';

export async function getComplianceMarkdown (
    frameworkId: number,
    data: ReportBodyData
  ) : Promise<any> {
    let rows: string;
    
    const complianceMD = `
VerifyWise compliance tracker report
========================

This report is generated by the VerifyWise Compliance Tracker. It aims to provide a way to demonstrate their claims about the risks of their AI systems.

- **Date** ${new Date().toLocaleDateString()}
- **Project** ${data.projectTitle}
- **Owner** ${data.projectOwner}


`
  return complianceMD;
}