/* 
    VerifyWise {name} report
    ========================

    This report is generated by the VeriftyWise {report-type}. It aims to provide a way to demonstrate their claims about the risks of their AI systems.
    
    - **Date** ${new Date().toLocaleDateString()}
    - **Project** ${data.projectTitle}
    - **Owner** ${data.projectOwner}
*/