/**
 * Generates a markdown report for vendor risks
 * @param projectId - The ID of the project
 * @param data - Project metadata including title and owner
 * @returns Promise<string> - Markdown formatted vendor risk report
 */

import { getUserByIdQuery } from "../../utils/user.utils";
import { getVendorByProjectIdQuery } from "../../utils/vendor.utils";
import { getVendorRisksByProjectIdQuery } from "../../utils/vendorRisk.util";
import { ReportBodyData } from "../reportService";

export async function getVendorReportMarkdown(
    projectId: number,
    data: ReportBodyData
  ): Promise<any> {
    const vendorReportData = await getVendorReportData(projectId);
    const riskReportData = await getVendorRiskReportData(projectId);
      
  return `
VerifyWise vendors and vendor risks report
-------------
This report is generated by VerifyWise. It aims to give information about the company's vendors and corresponding vendor risks.
  
- **Date**: ${new Date().toLocaleDateString()}
- **Project**: ${data.projectTitle}
- **Owner**: ${data.projectOwner}

Vendors table
-------------
| Vendor Name | Assignee | Review Status | Risk Status | Review Date |
|----|----|----|----|----|
${vendorReportData}

Vendor risk table
-------------
| Impact | Likelihood | Risk Severity | Action Owner | Risk Level | Risk Description |
|----|----|----|----|----|----|
${riskReportData}
`;
}

/**
 * Retrieves all vendor data by projectId from DB
 * @param projectId - The ID of the project
 * @returns Promise<string> - Vendor table
*/
export async function getVendorReportData(
  projectId: number
): Promise<String> {
  let vendorRows: string = ``;
  try {
    const vendorData = await getVendorByProjectIdQuery(projectId);
    vendorRows =
      vendorData && vendorData.length > 0
        ? await Promise.all(
            vendorData.map(async (vendor) => {
              const vendorAssignee = await getUserByIdQuery(vendor.assignee);
              return `| ${vendor.vendor_name} | ${vendorAssignee.name} ${
                vendorAssignee.surname
              } | ${vendor.review_status} | ${
                vendor.risk_status
              } | ${vendor.review_date.toLocaleDateString()} |`;
            })
          ).then((rows) => rows.join("\n"))
        : "| - | - | - | - | - |";
  } catch (error) {
    console.error(error);
    throw new Error(`Error while fetching the vendor risk report data`);  
  }

  return vendorRows;
}

/**
 * Retrieves all vendor risk data by projectId from DB
 * @param projectId - The ID of the project
 * @returns Promise<string> - Vendor risk table
*/
export async function getVendorRiskReportData(
  projectId: number
): Promise<String> {
  let riskRows: string = ``;
  try {
    const riskData = await getVendorRisksByProjectIdQuery(projectId);
    riskRows =
      riskData && riskData.length > 0
        ? await Promise.all(
            riskData.map(async (risk) => {
              const riskActionOwner = await getUserByIdQuery(risk.action_owner);
              return `| ${risk.impact} | ${risk.likelihood} | ${risk.risk_severity} | ${riskActionOwner.name} ${riskActionOwner.surname} | ${risk.risk_level} | ${risk.risk_description} |`;
            })
          ).then((rows) => rows.join("\n"))
        : "| - | - | - | - | - | - |";
  } catch (error) {
    console.error(error);
    throw new Error(`Error while fetching the vendor risk report data`);  
  }

  return riskRows;
}
  