export const ProjectScope = [
  {
    id: 1,
    title: "General",
    questions: [
      {
        id: 1,
        question: "Describe the AI environment/application used.",
        hint: "Describe the AI environment/application used.",
        priorityLevel: "high priority",
        answerType: "Long text",
        inputType: "Tiptap area",
        evidenceFileRequired: false,
        isRequired: true,
        evidenceFiles: [],
      },
      {
        id: 2,
        question: "Is a new form of AI technology used?",
        hint: "Is a new form of AI technology used?",
        priorityLevel: "high priority",
        answerType: "Long text",
        inputType: "Tiptap area",
        evidenceFileRequired: false,
        isRequired: true,
        evidenceFiles: [],
      },
      {
        id: 3,
        question: "Are personal sensitive data used?",
        hint: "Are personal sensitive data used?",
        priorityLevel: "high priority",
        answerType: "Long text",
        inputType: "Tiptap area",
        evidenceFileRequired: false,
        isRequired: true,
        evidenceFiles: [],
      },
      {
        id: 4,
        question: "Project scope documents description",
        hint: "Project scope documents description",
        priorityLevel: "high priority",
        answerType: "Long text",
        inputType: "Tiptap area",
        evidenceFileRequired: false,
        isRequired: true,
        evidenceFiles: [],
      },
    ],
  },
  {
    id: 2,
    title: "Technology details",
    questions: [
      {
        id: 1,
        question:
          "What type of AI technology are you using? Explain AI and ML technologies used.",
        hint: "What type of AI technology are you using? Explain AI and ML technologies used.",
        priorityLevel: "high priority",
        answerType: "Long text",
        inputType: "Tiptap area",
        evidenceFileRequired: false,
        isRequired: true,
        evidenceFiles: [],
      },
      {
        id: 2,
        question:
          "Is there ongoing monitoring of the system to ensure that the system is operating as intended?",
        hint: "Is there ongoing monitoring of the system to ensure that the system is operating as intended?",
        priorityLevel: "high priority",
        answerType: "Long text",
        inputType: "Tiptap area",
        evidenceFileRequired: false,
        isRequired: true,
        evidenceFiles: [],
      },
      {
        id: 3,
        question:
          "Have you considered unintended outcomes that could occur from the use of this system?",
        hint: "Have you considered unintended outcomes that could occur from the use of this system?",
        priorityLevel: "high priority",
        answerType: "Long text",
        inputType: "Tiptap area",
        evidenceFileRequired: false,
        isRequired: true,
        evidenceFiles: [],
      },
      {
        id: 4,
        question:
          "Add technology documentation. You can include a data flow diagram, MLops lifecycle diagram. Think of it as an executive summary of the technology you are using.",
        hint: "Add technology documentation. You can include a data flow diagram, MLops lifecycle diagram. Think of it as an executive summary of the technology you are using.",
        priorityLevel: "high priority",
        answerType: "Long text",
        inputType: "Tiptap area",
        evidenceFileRequired: false,
        isRequired: true,
        evidenceFiles: [],
      },
    ],
  },
];
