export type ProjectRisk = {
  id: number; // Auto generated by database
  project_id: number; // Foreign key to refer to the project
  risk_name: string; // Name assigned to the risk
  risk_owner: string; // Assigned owner responsible for the risk
  ai_lifecycle_phase: string; // AI lifecycle phase associated with the risk
  risk_description: string; // Detailed description of the risk
  risk_category: string; // Category the risk falls under
  impact: string; // Expected impact of the risk
  assessment_mapping: string; // Mapping of the risk assessment details
  controls_mapping: string; // Mapping of the controls associated with the risk
  likelihood: string; // Likelihood of the risk occurring
  severity: string; // Severity of the risk
  risk_level_autocalculated:
    | "No risk"
    | "Low risk"
    | "Medium risk"
    | "High risk"
    | "Very high risk"; // Auto calculated risk level based on inputs
  review_notes: string; // Notes added during the review
  mitigation_status: string; // Status of mitigation efforts
  current_risk_level: string; // Current evaluated risk level
  deadline: Date; // Due date for addressing the risk
  mitigation_plan: string; // Detailed mitigation plan to reduce the risk
  implementation_strategy: string; // Strategy for implementing the mitigation measures
  mitigation_evidence_document: string; // Document providing mitigation actions 
  likelihood_mitigation: string; // Mitigation measures to reduce likelihood
  risk_severity: string; // Updated severity after mitigation
  final_risk_level: string; // Final risk level after mitigation and review
  risk_approval: string; // Approval status of the risk assessment
  approval_status: string; // Final approval approval on the risk
  date_of_assessment: Date; // Date the risk assessment was conducted
};
