export type Subcontrol = {
  id?: number; // auto generated by database
  title: string; // gets assigned from the structure
  description: string; // gets assigned from the structure
  order_no?: number; // gets assigned from the structure
  status?: "Waiting" | "In progress" | "Done"; // won't get any values, will be filled by user
  approver?: string; // won't get any values, will be filled by user
  risk_review?: "Acceptable risk" | "Residual risk" | "Unacceptable risk"; // won't get any values, will be filled by user
  owner?: string; // won't get any values, will be filled by user
  reviewer?: string; // won't get any values, will be filled by user
  due_date?: Date; // won't get any values, will be filled by user
  implementation_details?: string; // won't get any values, will be filled by user
  evidence_description?: string; // won't get any values, will be filled by user
  feedback_description?: string; // won't get any values, will be filled by user
  evidence_files?: string[]; // fill be filed automatically when a file is uploaded
  feedback_files?: string[]; // fill be filed automatically when a file is uploaded
  control_id: number; // when control is created, its id will be stored and assign here as FK
};
