import {
  Column,
  DataType,
  ForeignKey,
  Model,
  Table,
} from "sequelize-typescript";
import { FrameworkModel } from "../../models/frameworks/frameworks.model";
import { AnnexCategoryISO } from "./annexCategoryISO.model";
import { AnnexCategoryStructISO } from "./annexCategoryStructISO.model";

export type AnnexStructISO = {
  id?: number; // auto generated by database
  title: string; // gets assigned from the structure
  annex_no?: number; // gets assigned from the structure
  framework_id?: number; // gets assigned from the structure
  annexcategories: Partial<AnnexCategoryISO & AnnexCategoryStructISO>[];
};

@Table({
  tableName: "annex_struct_iso",
})
export class AnnexStructISOModel extends Model<AnnexStructISO> {
  @Column({
    type: DataType.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  })
  id!: number;

  @Column({
    type: DataType.STRING,
  })
  title!: string;

  @Column({
    type: DataType.INTEGER,
  })
  annex_no?: number;

  @ForeignKey(() => FrameworkModel)
  @Column({
    type: DataType.INTEGER,
  })
  framework_id?: number;
}
