import {
  Column,
  DataType,
  ForeignKey,
  Model,
  Table,
} from "sequelize-typescript";
import { FrameworkModel } from "../../models/frameworks/frameworks.model";
import { SubClauseISO } from "./subClauseISO.model";
import { SubClauseStructISO } from "./subClauseStructISO.model";

export type ClauseStructISO = {
  id?: number; // auto generated by database
  title: string; // gets assigned from the structure
  clause_no: number; // gets assigned from the structure
  framework_id?: number; // gets assigned from the structure
  subclauses: Partial<SubClauseISO & SubClauseStructISO>[];
};

@Table({
  tableName: "clause_struct_iso",
})
export class ClauseStructISOModel extends Model<ClauseStructISO> {
  @Column({
    type: DataType.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  })
  id!: number;

  @Column({
    type: DataType.STRING,
  })
  title!: string;

  @Column({
    type: DataType.INTEGER,
  })
  clause_no!: number;

  @ForeignKey(() => FrameworkModel)
  @Column({
    type: DataType.INTEGER,
  })
  framework_id?: number;
}
