import {
  Column,
  DataType,
  ForeignKey,
  Model,
  Table,
} from "sequelize-typescript";
import { UserModel } from "../../models/user/user.model";
import { SubClauseStructISOModel } from "./subClauseStructISO.model";
import { ProjectFrameworksModel } from "../../models/projectFrameworks/projectFrameworks.model";
import { Status, STATUSES } from "../../../types/status.type";

export type SubClauseISO = {
  id?: number; // auto generated by database
  implementation_description: string;
  evidence_links: Object[];
  staus: Status;
  owner: number;
  reviewer: number;
  approver: number;
  due_date: Date;
  auditor_feedback: string;
  subclause_meta_id: number;
  projects_frameworks_id: number;
  created_at: Date;
  is_demo?: boolean;
};

@Table({
  tableName: "subclause_iso",
})
export class SubClauseISOModel extends Model<SubClauseISO> {
  @Column({
    type: DataType.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  })
  id?: number;

  @Column({
    type: DataType.STRING,
  })
  implementation_description!: string;

  @Column({
    type: DataType.JSONB,
  })
  evidence_links!: Object[];

  @Column({
    type: DataType.ENUM(...STATUSES),
  })
  staus!: Status;

  @ForeignKey(() => UserModel)
  @Column({
    type: DataType.INTEGER,
  })
  owner!: number;

  @ForeignKey(() => UserModel)
  @Column({
    type: DataType.INTEGER,
  })
  reviewer!: number;

  @ForeignKey(() => UserModel)
  @Column({
    type: DataType.INTEGER,
  })
  approver!: number;

  @Column({
    type: DataType.DATE,
  })
  due_date!: Date;

  @Column({
    type: DataType.STRING,
  })
  auditor_feedback!: string;

  @ForeignKey(() => SubClauseStructISOModel)
  @Column({
    type: DataType.INTEGER,
  })
  subclause_meta_id!: number;

  @ForeignKey(() => ProjectFrameworksModel)
  @Column({
    type: DataType.INTEGER,
  })
  projects_frameworks_id!: number;

  @Column({
    type: DataType.DATE,
    defaultValue: DataType.NOW,
  })
  created_at!: Date;

  @Column({
    type: DataType.BOOLEAN,
    defaultValue: false,
  })
  is_demo?: boolean;
}
