/*

This is the new Subtopic model(Schema) and will be replaced with the new one.
Please align other files with this

*/
export type Subtopic = {
  id?: number; // auto generated by database
  title: string; // gets assigned from the structure
  order_no?: number; // gets assigned from the structure
  topic_id: number; // when topic is created, its id will be stored and assign here as FK
};

// export type Subtopic = {
//   id: number;
//   topicId: number;
//   name: string;
//   orderNo: number;
// };
