import { Column, DataType, ForeignKey, Model, Table } from "sequelize-typescript";
import { TopicModel } from "./topic.model";

/*

This is the new Subtopic model(Schema) and will be replaced with the new one.
Please align other files with this

*/
export type Subtopic = {
  id?: number; // auto generated by database
  title: string; // gets assigned from the structure
  order_no?: number; // gets assigned from the structure
  topic_id: number; // when topic is created, its id will be stored and assign here as FK
  created_at?: Date;
};

@Table({
  tableName: "subtopics"
})
export class SubtopicModel extends Model<Subtopic> {
  @Column({
    type: DataType.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  })
  id?: number;

  @Column({
    type: DataType.STRING
  })
  title!: string;

  @Column({
    type: DataType.INTEGER
  })
  order_no?: number;

  @ForeignKey(() => TopicModel)
  @Column({
    type: DataType.INTEGER
  })
  topic_id!: number;

  @Column({
    type: DataType.BOOLEAN,
    allowNull: false,
    defaultValue: false
  })
  is_demo?: boolean;

  @Column({
    type: DataType.DATE
  })
  created_at?: Date;
}

