/*

This is the new Topic model(Schema) and will be replaced with the new one.
Please align other files with this

*/
export type Topic = {
  id?: number; // auto generated by database
  title: string; // gets assigned from the structure
  order_no?: number; // gets assigned from the structure
  assessment_id: number; // when assessment is created, its id will be stored and assign here as FK
};

// export type Topic = {
//   id: number;
//   assessmentId: number;
//   title: string;
//   orderNo: number;
// };
