export interface IQuestion {
  id?: number; // auto generated by database
  order_no?: number; // gets assigned from the structure
  question: string; // gets assigned from the structure
  hint: string; // gets assigned from the structure
  priority_level: "high priority" | "medium priority" | "low priority"; // gets assigned from the structure
  answer_type: string; // gets assigned from the structure
  input_type: string; // gets assigned from the structure
  evidence_required: boolean; // gets assigned from the structure
  is_required: boolean; // gets assigned from the structure
  dropdown_options?: any[]; // gets assigned from the structure
  evidence_files?: {
    id: string;
    fileName: string;
    project_id: number;
    uploaded_by: number;
    uploaded_time: Date;
  }[]; // gets assigned from the structure
  answer?: string; // won't get any values, will be filled by user
  subtopic_id: number; // when subtopic is created, its id will be stored and assign here as FK
  is_demo?: boolean;
  created_at?: Date;
  status?: "Not started" | "In progress" | "Done";
}
