export interface ISubtopic {
  id?: number; // auto generated by database
  title: string; // gets assigned from the structure
  order_no?: number; // gets assigned from the structure
  topic_id: number; // when topic is created, its id will be stored and assign here as FK
  created_at?: Date;
}
