export interface ITrainingRegister {
  id?: number; // auto generated by DB
  training_name: string;
  duration: string;
  provider: string;
  department: string;
  status: "Planned" | "In Progress" | "Completed";
  numberOfPeople: number;
  description: string;
}
