export interface IVendor {
  id?: number; // auto generated by database
  order_no?: number; // gets assigned from the structure (keeping for compatibility)
  projects?: any[]; // required by validation, but optional in interface for compatibility
  vendor_name: string; // won't get any values, will be filled by user
  vendor_provides: string; // won't get any values, will be filled by user
  assignee: number; // won't get any values, will be filled by user
  website: string; // won't get any values, will be filled by user
  vendor_contact_person: string; // won't get any values, will be filled by user
  review_result?: string; // optional field, can be filled by user
  review_status?:
    | "Not started"
    | "In review"
    | "Reviewed"
    | "Requires follow-up"; // optional field, can be filled by user
  reviewer?: number | null; // optional field, can be filled by user
  review_date?: Date; // optional field, can be filled by user
  created_at?: Date;
}
