export interface IVendor {
  id?: number; // auto generated by database
  order_no?: number; // gets assigned from the structure
  projects?: any[]; // won't get any values, will be filled by user
  vendor_name: string; // won't get any values, will be filled by user
  vendor_provides: string; // won't get any values, will be filled by user
  assignee: number; // won't get any values, will be filled by user
  website: string; // won't get any values, will be filled by user
  vendor_contact_person: string; // won't get any values, will be filled by user
  review_result: string; // won't get any values, will be filled by user
  review_status:
    | "Not started"
    | "In review"
    | "Reviewed"
    | "Requires follow-up"; // won't get any values, will be filled by user
  reviewer: number; // won't get any values, will be filled by user
  risk_status:
    | "Very high risk"
    | "High risk"
    | "Medium risk"
    | "Low risk"
    | "Very low risk"; // won't get any values, will be filled by user
  review_date: Date; // won't get any values, will be filled by user
  created_at?: Date;
}
